model: ../../models/base
train: true
data: data
fine_tune_type: lora
adapter_path: adapters
seed: 1731
num_layers: 12
batch_size: 2
iters: 120
learning_rate: 0.00005
max_seq_length: 2048
mask_prompt: true
steps_per_report: 10
steps_per_eval: 20
val_batches: -1
save_every: 20
lora_parameters:
  rank: 16
  scale: 16.0
  dropout: 0.1
