model: ../models/base
train: true
data: data
fine_tune_type: lora
adapter_path: adapters
seed: 314
num_layers: 12
batch_size: 2
iters: 300
learning_rate: 0.00005
max_seq_length: 2048
mask_prompt: true
steps_per_report: 25
steps_per_eval: 100
val_batches: -1
save_every: 100
lora_parameters:
  rank: 16
  scale: 16.0
  dropout: 0.05
