model: ../models/base
train: true
data: data
fine_tune_type: lora
adapter_path: adapters
seed: 73
num_layers: 16
batch_size: 4
iters: 400
learning_rate: 0.0001
max_seq_length: 256
mask_prompt: true
steps_per_report: 20
steps_per_eval: 100
val_batches: -1
save_every: 100
lora_parameters:
  rank: 16
  scale: 16.0
  dropout: 0.0
